language: ruby
rvm:
  - 2.7.6
  - 3.0.4
  - 3.1.2
before_install: gem install bundler -v 1.11.2
bundler_args: --jobs 3 --retry 3
cache: bundler
addons:
  code_climate:
    repo_token: 196df8880b27b92c2e879846ffb08040eee02248297a0c9fd0a1e071ea031f28
